apiVersion : apps/v1
kind: Deployment
metadata:
  name: ajaymithireddyfrontendnew 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ajaymithireddyfrontendnew
  template:
    metadata:
      labels:
        app: ajaymithireddyfrontendnew 
    spec:
      containers:
        - name: ajaymithireddyfrontendnew 
          image: myregi.azurecr.io/frontendnew
          ports:
          - containerPort: 4200
